name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate full contribution calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ github.token }}
          committer_token: ${{ github.token }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
